using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.Collections;

public class QuestionData
{
    public string[] questions = 
    {
        "How old do they look?",
        "Who (or what) is their style icon?",
        "What was their first word?",
        "Who is their one true love?",
        "What will be written on their gravestone?",
        "What is their best feature?",
        "What would they taste like?",
        "What is their hidden talent?",
        "What is their greatest fear?",
        "If the world was ending, how would they spend their last day?",
        "What animal do they look like?",
        "What will their last word be?",
        "What is their password?",
        "What is their 'secret' dream job?",
        "What are they terrible at?",
        "What question would they hate to answer?",
        "What should their catchphrase be?",
        "Which evil villain do they remind you of?",
        "What are they most ashamed about?",
        "What will they be remembered for?",
        "Describe the sound of their voice in one word?",
        "What did they last cry about?",
        "What do they have nightmares about?",
        "What would they delete from their internet history?",
        "If they were a cooking utensil, what would it be?",
        "Where will they be in ten years time?",
        "If they kept a locket, what photo would be inside it?",
        "Which actor would play them in a film?",
        "What is their guilty pleasure?",
        "If they were a song, what would it be?",
        "How do they 'really' spend their weekends?",
        "What pet name did they have as a child?",
        "Where would they feel most out of place?",
        "What is their number one passion in life?",
        "If you had a baby with them, what would you call it?",
        "Which cartoon character do they look like?",
        "How will they die?",
        "What would you but them in a secret santa?",
        "If they had a superpower, what would it be?",
        "Which three word best describe this person?",
        "If they were a DJ, what would their name be?",
        "What do they desperately need in their life?",
        "What did you think when you first met this person?",
        "What is the last illegal act they committed?",
        "What do they complain about the most?",
        "What is the first thing they do in the morning?",
        "If they came with instruction, what would they say?",
        "Who did they last message? (And what did it say?)",
        "If you didn't know them, what would you think their name is?",
        "if they were a genre of music, what would it be?",
        "If they won the lottery, what would they buy first?",
        "What was their nickname at school?",
        "What do they secretly collect?",
        "Who would they push off a cliff?",
        "Who would push THEM off a cliff?",
        "What one thing do they hate the most? (In one word.)",
        "If they were a dessert, what would they be?",
        "What can they do better than anyone else in the room?",
        "What do they think when they look in the mirror?",
        "If they released a fragrance, what would it be called?",
        "What is their favorite body part and what nickname do they give it?",
        "If they hosted a TV talk show, what would it be called?",
        "If they broke a World Record, what would it be?",
        "What are they most likely to go to jail for?",
        "Who is their secret guilty crush?",
        "If they could be anywhere right now, where would they be?",
        "What do they wish they could say to \"<leftPlayer>?\"",
        "What though goes through their mind at last once a day?",
        "What is in the 'recently deleted' section of their phone photos?",
        "If they had a signature dance move, what would it be called?",
        "If they had a YouTube channel, what would it be about?",
        "If they were a dictator, what would their first law be?",
        "What would be their weapon of choice in a zombie apocalypse?",
        "If there was a documentary film about them, what would it be called?",
        "Who would they choose to be their sidekick?",
        "if they could only take one thing to a desert island, what would it be?",
        "If they were a sauce, what would they be?",
        "If they were a god, what would they be the god of?",
        "Where would they take someone of a first data?",
        "What imaginary sport would they get a gold medal in?",
        "If they were a painting what would the painting be called?",
        "What three ingredients would be in their dream sandwich?",
        "Describe their face in three words?",
        "What pick-up line would always work on them?",
        "What's the first thing they'd do if they had the power of invisibility?",
        "If they were an inventor, what would they invent first?",
        "Who are their 'real' parents?",
        "Sum up their odor in two words?",
        "Who would they be in Harry Potter?",
        "Which vegetable do they look like?",
        "What is one thing they will never accomplish in their lifetime?",
        "How would they describe you?",
        "If they could upgrade their body with just one gadget, what would it be?",
        "Finish this poem about them: \"Roses are red, Violets are blue...\"",
        "If they were reincarnated, what would they come back as?",
        "Which word do they use far too often?",
        "If they designed the license plate on their car, what would it say?",
        "What is their imaginary friend called?",
        "What skill do they absolutely NOT possess?",
        "If they were a Transformer, what vehicle would they transform into?",
        "What should the hobbies section of their profile page say?",
        "If they could replace a body part with an animal's, what would they choose?",
        "What would be their dream romantic date activity?",
        "if they started a religion, what would it be called?",
        "What did their parents shout out the moment they were born?",
        "What does their horoscope probably say about them today?",
        "Which form of torture would make them confess everthing?",
        "If they woke up in your body, what would they do?",
        "In one word, describe their taste in partners.",
        "If they ran for government, what would their slogan be??",
        "If they were an item on the McDonald's menu, what would they be?",
        "What unlikely item might you find in their body if you X-rayed them?",
        "if they were on a date from hell, how would they get out of it?",
        "What do they secretly have a tattoo of and where is it?",
        "What would be their wrestling name and the name of their signature move?",
        "What advice will they give youngsters when they are old and gray?",
        "If they were a kind of weather, what would it be?",
        "What did they dream about last night?",
        "What would their embarrassing old online username be?",
        "In a word, describe the way they hug.?",
        "If they were on the front page of a newspaper, what would be the headline?",
        "If you could change one thing about them, what would it be?",
        "They have a mysterious key. What is it for?",
        "What should be the latin name for this person?",
        "What wouldn't they do for a 'million' dollars?",
        "What is in the secret folder on their computer?",
        "If they were a professor, what would they teach?",
        "What would their restaurant be called?",
        "What can't they be trusted with?",
        "What is the last thing they look at on their phone before they sleep?",
        "What would they sell their soul for?",
        "They have a cool scar on their face. How did they get it?",
        "If they could have any animal as a pet, what would it be?",
        "If they were a can of paint, what would the color be called?",
        "What film represents their life the best?",
        "If they were an app, which would they be?",
        "If they had a private island, what would it be called?",
        "What one thing would they save from a fire?",
        "If they could time travel, where would they go?",
        "What is a terrible habit of theirs that they really need to work on"
    };

    //QuestionData(bool defaultQuestions)
    //{
    //    if(defaultQuestions)
    //    {
    //        questions = new string[10];
    //    }
    //}
}
